<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Exn (eio.Eio.Exn)</title><meta charset="utf-8"/><link rel="stylesheet" href="../../../odoc.support/odoc.css"/><meta name="generator" content="odoc 2.0.0-823-ge94c197"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../../odoc.support/highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body class="odoc"><nav class="odoc-nav"><a href="../index.html">Up</a> â€“ <a href="../../index.html">eio</a> &#x00BB; <a href="../index.html">Eio</a> &#x00BB; Exn</nav><header class="odoc-preamble"><h1>Module <code><span>Eio.Exn</span></code></h1><p>Eio exceptions.</p></header><div class="odoc-content"><div class="odoc-spec"><div class="spec type anchored" id="type-with_bt"><a href="#type-with_bt" class="anchor"></a><code><span><span class="keyword">type</span> with_bt</span><span> = exn * <span class="xref-unresolved">Stdlib</span>.Printexc.raw_backtrace</span></code></div></div><div class="odoc-spec"><div class="spec type anchored" id="type-err"><a href="#type-err" class="anchor"></a><code><span><span class="keyword">type</span> err</span><span> = </span><span>..</span></code></div><div class="spec-doc"><p>Describes the particular error that occurred.</p><p>They are typically nested (e.g. <code>Fs (Permission_denied (Unix_error ...))</code>) so that you can match e.g. all IO errors, all file-system errors, all permission denied errors, etc.</p><p>If you extend this, use <a href="#val-register_pp"><code>register_pp</code></a> to add a printer for the new error.</p></div></div><div class="odoc-spec"><div class="spec type anchored" id="type-context"><a href="#type-context" class="anchor"></a><code><span><span class="keyword">type</span> context</span></code></div><div class="spec-doc"><p>Extra information attached to an IO error. This provides contextual information about what caused the error.</p></div></div><div class="odoc-spec"><div class="spec exception anchored" id="exception-Io"><a href="#exception-Io" class="anchor"></a><code><span><span class="keyword">exception</span> </span><span><span class="exception">Io</span> <span class="keyword">of</span> <a href="#type-err">err</a> * <a href="#type-context">context</a></span></code></div><div class="spec-doc"><p>A general purpose IO exception.</p><p>This is used for most errors interacting with the outside world, and is similar to <code>Unix.Unix_error</code>, but more general. An unknown <code>Io</code> error should typically be reported to the user, but does not generally indicate a bug in the program.</p></div></div><div class="odoc-spec"><div class="spec type extension anchored" id="extension-decl-Multiple_io"><a href="#extension-decl-Multiple_io" class="anchor"></a><code><span><span class="keyword">type</span> <a href="#type-err">err</a> += </span></code><ol><li id="extension-Multiple_io" class="def variant extension anchored"><a href="#extension-Multiple_io" class="anchor"></a><code><span>| </span><span><span class="extension">Multiple_io</span> <span class="keyword">of</span> <span><span>(<a href="#type-err">err</a> * <a href="#type-context">context</a> * <span class="xref-unresolved">Stdlib</span>.Printexc.raw_backtrace)</span> list</span></span></code><div class="def-doc"><span class="comment-delim">(*</span><p>Error code used when multiple IO errors occur.</p><p>This is useful if you want to catch and report all IO errors.</p><span class="comment-delim">*)</span></div></li></ol></div></div><div class="odoc-spec"><div class="spec value anchored" id="val-create"><a href="#val-create" class="anchor"></a><code><span><span class="keyword">val</span> create : <span><a href="#type-err">err</a> <span class="arrow">&#45;&gt;</span></span> exn</span></code></div><div class="spec-doc"><p><code>create err</code> is an <a href="#exception-Io"><code>Io</code></a> exception with an empty context.</p></div></div><div class="odoc-spec"><div class="spec value anchored" id="val-add_context"><a href="#val-add_context" class="anchor"></a><code><span><span class="keyword">val</span> add_context : 
  <span>exn <span class="arrow">&#45;&gt;</span></span>
  <span><span><span>(<span class="type-var">'a</span>, <span class="xref-unresolved">Stdlib</span>.Format.formatter, unit, exn)</span> <span class="xref-unresolved">Stdlib</span>.format4</span> <span class="arrow">&#45;&gt;</span></span>
  <span class="type-var">'a</span></span></code></div><div class="spec-doc"><p><code>add_context ex msg</code> returns a new exception with <code>msg</code> added to <code>ex</code>'s context, if <code>ex</code> is an <a href="#exception-Io"><code>Io</code></a> exception.</p><p>If <code>ex</code> is not an <code>Io</code> exception, this function just returns the original exception.</p></div></div><div class="odoc-spec"><div class="spec value anchored" id="val-reraise_with_context"><a href="#val-reraise_with_context" class="anchor"></a><code><span><span class="keyword">val</span> reraise_with_context : 
  <span>exn <span class="arrow">&#45;&gt;</span></span>
  <span><span class="xref-unresolved">Stdlib</span>.Printexc.raw_backtrace <span class="arrow">&#45;&gt;</span></span>
  <span><span><span>(<span class="type-var">'a</span>, <span class="xref-unresolved">Stdlib</span>.Format.formatter, unit, <span class="type-var">'b</span>)</span> <span class="xref-unresolved">Stdlib</span>.format4</span> <span class="arrow">&#45;&gt;</span></span>
  <span class="type-var">'a</span></span></code></div><div class="spec-doc"><p><code>reraise_with_context ex bt msg</code> raises <code>ex</code> extended with additional information <code>msg</code>.</p><p><code>ex</code> should be an <a href="#exception-Io"><code>Io</code></a> exception (if not, is re-raised unmodified).</p><p>Example:</p><pre class="language-ocaml"><code>try connect addr
with Eio.Io _ as ex -&gt;
  let bt = Printexc.get_raw_backtrace () in
  reraise_with_context ex bt &quot;connecting to %S&quot; addr</code></pre><p>You must get the backtrace before calling any other function in the exception handler to prevent corruption of the backtrace.</p></div></div><div class="odoc-spec"><div class="spec value anchored" id="val-register_pp"><a href="#val-register_pp" class="anchor"></a><code><span><span class="keyword">val</span> register_pp : <span><span>(<span><span class="xref-unresolved">Stdlib</span>.Format.formatter <span class="arrow">&#45;&gt;</span></span> <span><a href="#type-err">err</a> <span class="arrow">&#45;&gt;</span></span> bool)</span> <span class="arrow">&#45;&gt;</span></span> unit</span></code></div><div class="spec-doc"><p><code>register_pp pp</code> adds <code>pp</code> as a pretty-printer of errors.</p><p><code>pp f err</code> should format <code>err</code> using <code>f</code>, if possible. It should return <code>true</code> on success, or <code>false</code> if it didn't recognise <code>err</code>.</p></div></div><div class="odoc-spec"><div class="spec value anchored" id="val-pp"><a href="#val-pp" class="anchor"></a><code><span><span class="keyword">val</span> pp : <span>exn <span class="xref-unresolved">Fmt</span>.t</span></span></code></div><div class="spec-doc"><p><code>pp</code> is a formatter for exceptions.</p><p>This is similar to <code>Fmt.exn</code>, but can do a better job on <a href="#exception-Io"><code>Io</code></a> exceptions because it can format them directly without having to convert to a string first.</p></div></div><div class="odoc-spec"><div class="spec value anchored" id="val-pp_err"><a href="#val-pp_err" class="anchor"></a><code><span><span class="keyword">val</span> pp_err : <span><a href="#type-err">err</a> <span class="xref-unresolved">Fmt</span>.t</span></span></code></div><div class="spec-doc"><p><code>pp_err</code> formats an error code.</p></div></div><div class="odoc-spec"><div class="spec module anchored" id="module-Backend"><a href="#module-Backend" class="anchor"></a><code><span><span class="keyword">module</span> <a href="Backend/index.html">Backend</a></span><span> : <span class="keyword">sig</span> ... <span class="keyword">end</span></span></code></div><div class="spec-doc"><p>Extensible backend-specific exceptions.</p></div></div><div class="odoc-spec"><div class="spec type extension anchored" id="extension-decl-X"><a href="#extension-decl-X" class="anchor"></a><code><span><span class="keyword">type</span> <a href="#type-err">err</a> += </span></code><ol><li id="extension-X" class="def variant extension anchored"><a href="#extension-X" class="anchor"></a><code><span>| </span><span><span class="extension">X</span> <span class="keyword">of</span> <a href="Backend/index.html#type-t">Backend.t</a></span></code><div class="def-doc"><span class="comment-delim">(*</span><p>A top-level code for backend errors that don't yet have a cross-platform classification in Eio.</p><p>You should avoid matching on these (in portable code). Instead, request a proper Eio code for them.</p><span class="comment-delim">*)</span></div></li></ol></div></div><div class="odoc-spec"><div class="spec exception anchored" id="exception-Multiple"><a href="#exception-Multiple" class="anchor"></a><code><span><span class="keyword">exception</span> </span><span><span class="exception">Multiple</span> <span class="keyword">of</span> <span><a href="#type-with_bt">with_bt</a> list</span></span></code></div><div class="spec-doc"><p>Raised if multiple fibers fail, to report all the exceptions.</p><p>This usually indicates a bug in the program.</p><p>Note: If multiple <b>IO</b> errors occur, then you will get <code>Io (Multiple_io _, _)</code> instead of this.</p></div></div><div class="odoc-spec"><div class="spec value anchored" id="val-combine"><a href="#val-combine" class="anchor"></a><code><span><span class="keyword">val</span> combine : <span><a href="#type-with_bt">with_bt</a> <span class="arrow">&#45;&gt;</span></span> <span><a href="#type-with_bt">with_bt</a> <span class="arrow">&#45;&gt;</span></span> <a href="#type-with_bt">with_bt</a></span></code></div><div class="spec-doc"><p><code>combine x y</code> returns a single exception and backtrace to use to represent two errors.</p><p>The resulting exception is typically just <code>Multiple [y; x]</code>, but various heuristics are used to simplify the result:</p><ul><li>Combining with a <a href="../Cancel/index.html#exception-Cancelled"><code>Cancel.Cancelled</code></a> exception does nothing, as these don't need to be reported. The result is only <code>Cancelled</code> if there is no other exception available.</li><li>If both errors are <code>Io</code> errors, then the result is <code>Io (Multiple_io _)</code>.</li></ul></div></div></div></body></html>
